sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.3
  - 2.6.5

gemfile:
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile

services:
  - postgresql
env:
  - WAZOWSKI_PG_DATABASE=travis_ci_test WAZOWSKI_PG_USERNAME=postgres
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres