name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    name: Test against Ruby ${{ matrix.ruby-version }} / Rails ${{ matrix.rails }}

    strategy:
      matrix:
        ruby-version: ['3.1', '3.0', '2.7']
        rails: ['6.0', '6.1']

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install gems
        env:
          MATRIX_RAILS_VERSION: ${{ matrix.rails }}
        run: |
          export BUNDLE_GEMFILE="${GITHUB_WORKSPACE}/gemfiles/${MATRIX_RAILS_VERSION}.gemfile"
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Run tests
        env:
          WAZOWSKI_PG_DATABASE: ci_db_test
          WAZOWSKI_PG_USERNAME: postgres
          WAZOWSKI_PG_PASSWD: postgres
          WAZOWSKI_PG_HOST: localhost
          WAZOWSKI_PG_PORT: 5432
        run: bundle exec rake